default: &default
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    # max_age: <%= 60.days.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

test:
  <<: *default

production:
  database: cache
  <<: *default

development:
  <<: *default
  database: cache
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    # max_age: <%= 60.days.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>
    max_age: 1.week
    max_entry_size: 10.megabytes


# test:
#   <<: *default

# production:
#   database: cache
#   <<: *default

